# -*- coding: utf-8 -*-
"""Copy of anac.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vYaZDhGXRYlw-isEgYo76GaUXhSNjizw
"""

import os
import pandas as pd
os.chdir("/home/laura/Downloads")
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np

voos = pd.read_csv('Dados_Estatisticos.csv')

voos.head()

voos.shape

voos.isnull().sum()

voos = voos.dropna()

voos.isnull().sum()

voos.dtypes

print(voos.columns)

voos['AEROPORTO_DE_ORIGEM_NOME'].unique()

voos['AEROPORTO_DE_ORIGEM_NOME'].nunique()

voos['AEROPORTO_DE_ORIGEM_NOME'].value_counts()

voos.loc[(voos['AEROPORTO_DE_ORIGEM_NOME'] == 'BARREIRAS') & (voos["ANO"] ==2021)]

print(voos.info())

voos.describe()

voos_ba = voos.loc[(voos['AEROPORTO_DE_ORIGEM_NOME'] == 'BARREIRAS') & (voos["ANO"] ==2022)]

voos_ba.describe()

janela = plt.figure(figsize=(10,5))
grafico = janela.add_axes([0, 0, 1, 1]) #começa com 0 no x, 0 no y, largura e altura 1
sns.set_theme(style="darkgrid")

grafico.plot(voos['MES'],voos['DECOLAGENS'])

voos_destinos = voos_ba.groupby('AEROPORTO_DE_DESTINO_REGIAO')['DECOLAGENS'].sum().reset_index()

voos_destinos.head()

plt.xticks(rotation=45)

sns.barplot(data=voos_destinos,x='AEROPORTO_DE_DESTINO_REGIAO',y='DECOLAGENS')
plt.show()

sns.histplot(data=voos_ba,x='PASSAGEIROS_PAGOS',bins=5)
plt.show()

voos_ba['GRUPO_DE_VOO'].value_counts()

sns.countplot(data=voos_ba,x='GRUPO_DE_VOO')
plt.show()

sns.boxplot(data=voos_ba, x='DECOLAGENS')
plt.show()

voos_ba['DECOLAGENS'].describe()

voos_ba.head()

sns.lmplot(data=voos_ba, x='CARGA_PAGA_KG', y='DISTANCIA_VOADA_KM')
plt.show()

sns.lmplot(data=voos_ba, x='CARGA_GRATIS_KG', y='DISTANCIA_VOADA_KM')
plt.show()

voos_nacionalidade = voos.groupby('EMPRESA_NACIONALIDADE')['DECOLAGENS'].sum().reset_index()
sns.barplot(data=voos_nacionalidade,x='EMPRESA_NACIONALIDADE',y='DECOLAGENS')
plt.show()

voos_fn = voos.loc[(voos['AEROPORTO_DE_ORIGEM_NOME'] == 'FERNANDO DE NORONHA') & (voos["ANO"] ==2021)]

voos_fn.head()

sns.lineplot(data=voos_fn, x='MES', y='DECOLAGENS', color='red')
plt.show()

sns.boxplot(data=voos_fn, x='DECOLAGENS')
plt.show()

voos_destinos = voos.groupby('AEROPORTO_DE_DESTINO_REGIAO')['DECOLAGENS'].sum().reset_index()
plt.xticks(rotation=45)

sns.barplot(data=voos_destinos,x='AEROPORTO_DE_DESTINO_REGIAO',y='DECOLAGENS')
plt.show()

sns.countplot(data=voos_fn,x='GRUPO_DE_VOO')
plt.show()

sns.histplot(data=voos_fn,x='PASSAGEIROS_PAGOS',bins=5)
plt.show()

janela, graficos = plt.subplots(nrows=3, ncols=2, figsize=(20,10))
plt.tight_layout()

sns.boxplot(data=voos_fn, x='DECOLAGENS', ax=graficos[0][0])
sns.boxplot(data=voos_ba, x='DECOLAGENS', ax=graficos[0][1])
sns.lineplot(data=voos_fn, x='MES', y='DECOLAGENS', color='red',ax=graficos[1][0])
sns.lineplot(data=voos_ba, x='MES', y='DECOLAGENS', color='red',ax=graficos[1][1])
sns.histplot(data=voos_fn,x='PASSAGEIROS_PAGOS',bins=5, ax=graficos[2][0])
sns.histplot(data=voos_ba,x='PASSAGEIROS_PAGOS',bins=5, ax=graficos[2][1])

janela